language: cpp

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:henriquegemignani/uspgamedev
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --force-yes g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

compiler:
  - gcc
  - clang

script:
  - cmake . -DROGUELIKE_INTERNAL_UGDK=On
  - make roguelike

notifications:
  email:
    - travis@uspgamedev.org