SET(GAME_SRCS 
    ./src/game/action/aim.cc 
    ./src/game/action/aim.h 
    ./src/game/action/skill/generic.cc 
    ./src/game/action/skill/generic.h 
    ./src/game/action/skill/movement.cc 
    ./src/game/action/skill/movement.h 
    ./src/game/action/skill/movement_place.cc 
    ./src/game/action/skill/movement_place.h 
    ./src/game/action/skill/movement_step.cc 
    ./src/game/action/skill/movement_step.h 
    ./src/game/action/skill/self.cc 
    ./src/game/action/skill/self.h 
    ./src/game/action/skill/self_damage.cc 
    ./src/game/action/skill/self_damage.h 
    ./src/game/action/skill/self_lightvision.cc 
    ./src/game/action/skill/self_lightvision.h 
    ./src/game/action/skill/simple.cc 
    ./src/game/action/skill/simple.h 
    ./src/game/action/skill/simple_fireat.cc 
    ./src/game/action/skill/simple_fireat.h 
    ./src/game/action/skill/skill.cc 
    ./src/game/action/skill/skill.h 
    ./src/game/action/skill/skillmanager.cc 
    ./src/game/action/skill/skillmanager.h 
    ./src/game/action/time/timeelapsed.h 
    ./src/game/action/time/timemanager.cc 
    ./src/game/action/time/timemanager.h 
    ./src/game/action.h 
    ./src/game/alg/equationalline.cc 
    ./src/game/alg/equationalline.h 
    ./src/game/alg/equationallinedouble.cc 
    ./src/game/alg/equationallinedouble.h 
    ./src/game/alg/los/cone.cc 
    ./src/game/alg/los/cone.h 
    ./src/game/alg/los/evenoctantiterator.cc 
    ./src/game/alg/los/evenoctantiterator.h 
    ./src/game/alg/los/eye.cc 
    ./src/game/alg/los/eye.h 
    ./src/game/alg/los/octant.cc 
    ./src/game/alg/los/octant.h 
    ./src/game/alg/los/octantiterator.h 
    ./src/game/alg/los/octantprocessor.cc 
    ./src/game/alg/los/octantprocessor.h 
    ./src/game/alg/los/oddoctantiterator.cc 
    ./src/game/alg/los/oddoctantiterator.h 
    ./src/game/alg/los/processor.cc 
    ./src/game/alg/los/processor.h 
    ./src/game/alg.h 
    ./src/game/base/gamecontroller.cc 
    ./src/game/base/gamecontroller.h 
    ./src/game/base/gameobject.cc 
    ./src/game/base/gameobject.h 
    ./src/game/base/gamething.h 
    ./src/game/base/gametile.cc 
    ./src/game/base/gametile.h 
    ./src/game/base/levelmanager.cc 
    ./src/game/base/levelmanager.h 
    ./src/game/base.h 
    ./src/game/builder/objectbuilder.cc 
    ./src/game/builder/objectbuilder.h 
    ./src/game/builder.h 
    ./src/game/component/componentbase.h 
    ./src/game/component/controller.cc 
    ./src/game/component/controller.h 
    ./src/game/component/controller_ai.cc 
    ./src/game/component/controller_ai.h 
    ./src/game/component/controller_idle.cc 
    ./src/game/component/controller_idle.h 
    ./src/game/component/controller_player.cc 
    ./src/game/component/controller_player.h 
    ./src/game/component/damageable.cc 
    ./src/game/component/damageable.h 
    ./src/game/component/energy.h 
    ./src/game/component/graphic.cc 
    ./src/game/component/graphic.h 
    ./src/game/component/graphic_rectangular.cc 
    ./src/game/component/graphic_rectangular.h 
    ./src/game/component/shape.h 
    ./src/game/component/shape_rectangular.cc 
    ./src/game/component/shape_rectangular.h 
    ./src/game/component/vision.cc 
    ./src/game/component/vision.h 
    ./src/game/component.h 
    ./src/game/config.h 
    ./src/game/ui/cursor.cc 
    ./src/game/ui/cursor.h 
    ./src/main.cc 
    ./src/utils/integer2Dutils.cc 
    ./src/utils/integer2Dutils.h 
    ./src/utils/utils.cc 
    ./src/utils/utils.h 
)
